export const FETCH_CHARACTERS_REQUEST = "FETCH_CHARACTERS_REQUEST";
export const FETCH_CHARACTERS_SUCCESS = "FETCH_CHARACTERS_SUCCESS";
export const FETCH_CHARACTERS_FAILURE = "FETCH_CHARACTERS_FAILURE";
export const UPDATE_CHARACTER_REQUEST = "UPDATE_CHARACTER_REQUEST";
export const UPDATE_CHARACTER_SUCCESS = "UPDATE_CHARACTER_SUCCESS";
export const UPDATE_CHARACTER_FAILURE = "UPDATE_CHARACTER_FAILURE";