export const FECTH_EVENTS_REQUEST = "FECTH_EVENTS_REQUEST";
export const FECTH_EVENTS_SUCCESS = "FECTH_EVENTS_SUCCESS";
export const FECTH_EVENTS_FAILURE = "FECTH_EVENTS_FAILURE";
export const ADD_EVENTS_SUCCESS = "ADD_EVENTS_SUCCESS";
export const ADD_EVENTS_FAILURE = "ADD_EVENTS_FAILURE";
export const ADD_EVENTS_REQUEST = "ADD_EVENTS_REQUEST";